import { HomeIcon, FileText, Users, HelpCircle } from "lucide-react";
import { FcBriefcase, FcProcess, FcReading } from "react-icons/fc";
import { FaTools, FaChartBar, FaBullhorn, FaComments } from "react-icons/fa";

const K = {
  FEATURES: [
    {
      title: "Job Simulations",
      description:
        "Participate in role based simulations tailored to your field.",
    },
    {
      title: "Internship & Job Board",
      description:
        "Explore and apply to real opportunities provided by partner companies.",
    },
    {
      title: "Mentor Assistance",
      description: "Access expert guidance from mentors during simulations.",
    },
    {
      title: "E-Certificates",
      description:
        "Earn downloadable,verifiable certificates with each simulation.",
    },
  ],
  TEAM: [
    {
      name: "Ebo Rice",
      role: "Back-end Developer",
      imageUrl: "https://via.placeholder.com/150",
      bio: "Back-end developer learning and growing with every build.",
    },
    {
      name: "Juliet Esinam",
      role: "Back-end Developer",
      imageUrl: "https://via.placeholder.com/150",
      bio: "Back-end developer learning and growing with every build.",
    },
    {
      name: "Jedidah Roberts",
      role: "Front-end Developer",
      imageUrl: "https://via.placeholder.com/150",
      bio: "Passionate about creating stunning UIs using React and Tailwind CSS.",
    },
    {
      name: "Jennifer Offin",
      role: "Front-end Developer",
      imageUrl: "https://via.placeholder.com/150",
      bio: "Crafts clean user interfaces with React and Tailwind CSS.",
    },
  ],

  USERLINKS: [
    {
      text: "ABOUT",
      dropdown: true,
      path: "/about",
      children: [
        { text: "OUR MISSION", path: "/about/mission" },
        { text: "THE TEAM", path: "/about/team" },
      ],
    },
    {
      text: "SIMULATIONS",
      path: "/simulations",
    },
    {
      text: "INTERNSHIPS",
      path: "/internship",
    },
    {
      text: "RECRUITERS",
      path: "/recruiter-dashboard",
    },
    {
      text: "MENTORSHIPS",
      path: "/mentorship",
    },
    {
      text: "CONTACT",
      path: "/contact",
    },
  ],

  NAVLINKS: [
    {
      icon: <HomeIcon />,
      text: "DASHBOARD",
      path: "/recruiter-dashboard",
    },
    {
      icon: <FcReading />,
      text: "MY SIMULATIONS",
      path: "/dashboard/simulations",
    },
    {
      icon: <FcBriefcase />,
      text: "MY APPLICATIONS",
      path: "/dashboard/applications",
    },
    {
      icon: <FileText />,
      text: "CERTIFICATES",
      path: "/dashboard/certificates",
    },
    {
      icon: <Users />,
      text: "MY TEAM",
      path: "/dashboard/team",
    },
    {
      icon: <HelpCircle />,
      text: "NEED HELP?",
      path: "/dashboard/help",
    },
  ],

  RECRUITERLINKS: [
    {
      icon: <HomeIcon />,
      text: "PROFILE",
      path: "/recruiters-profile",
    },
    {
      icon: <HomeIcon />,
      text: "DASHBOARD",
      path: "/recruiter-dashboard",
    },
    {
      icon: <FcReading />,
      text: "MY SIMULATIONS",
      path: "/recruiter/simulations",
    },
    {
      icon: <FcBriefcase />,
      text: "WANT TO ADD A SIMULATION",
      path: "/add-simulation",
    },

    {
      icon: <HelpCircle />,
      text: "NEED HELP?",
      path: "/dashboard/help",
    },
  ],
  ADMINLINKS: [
    {
      icon: <HomeIcon />,
      text: "ADMIN DASHBOARD",
      path: "/admin/dashboard",
    },
    {
      icon: <Users />,
      text: "USERS",
      path: "/admin/users",
    },
    {
      icon: <FcReading />,
      text: "SIMULATIONS",
      path: "/admin/simulations",
    },
    {
      icon: <FcBriefcase />,
      text: "INTERNSHIPS",
      path: "/admin/internships",
    },
  ],
  JOBSIMULATIONS: [
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752497383/upskill/jobSims/cnjviu8l2f8sshhmnqrm.jpg",
      imagePublicId: "upskill/jobSims/cnjviu8l2f8sshhmnqrm",
      title: "Legal Case Research ",
      description:
        "Step into the role of a junior legal associate conducting case research, preparing summaries, and briefing senior attorneys.",
      field: "Law",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [
        "Review case files related to intellectual property disputes",
        "Conduct legal research using online databases",
        "Summarize and analyze legal precedents",
        "Prepare a one-page brief for a senior attorney",
        "Organize findings into a research memo",
      ],
      participants: [],
      level: "Beginner",
      duration: 4,
      reviews: [],
      isHiring: false,
      isPublished: false,
      _id: "6874fce8f7bc8115606f2dd5",
      createdAt: "2025-07-14T12:49:44.297Z",
      updatedAt: "2025-07-14T12:49:44.297Z",
      __v: 0,
      overview:
        "In this simulation, you'll gain insight into the legal industry by conducting in-depth research, analyzing case law, and supporting senior lawyers with documentation. This program will help you build confidence in handling legal information critically and professionally.",
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752497383/upskill/jobSims/cnjviu8l2f8sshhmnqrm.jpg",
      imagePublicId: "upskill/jobSims/cnjviu8l2f8sshhmnqrm",
      title: "Legal Case Research ",
      description:
        "Step into the role of a junior legal associate conducting case research, preparing summaries, and briefing senior attorneys.",
      field: "Law",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Beginner",
      duration: 4,
      reviews: [],
      isHiring: false,
      isPublished: false,
      _id: "6874fce8f7bc8115606f2dd5",
      createdAt: "2025-07-14T12:49:44.297Z",
      updatedAt: "2025-07-14T12:49:44.297Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752497383/upskill/jobSims/cnjviu8l2f8sshhmnqrm.jpg",
      imagePublicId: "upskill/jobSims/cnjviu8l2f8sshhmnqrm",
      title: "Legal Case Research ",
      description:
        "Step into the role of a junior legal associate conducting case research, preparing summaries, and briefing senior attorneys.",
      field: "Law",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Beginner",
      duration: 4,
      reviews: [],
      isHiring: false,
      isPublished: false,
      _id: "6874fce8f7bc8115606f2dd5",
      createdAt: "2025-07-14T12:49:44.297Z",
      updatedAt: "2025-07-14T12:49:44.297Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752497827/upskill/jobSims/pdo1pgycxzrrt7dlnhtc.jpg",
      imagePublicId: "upskill/jobSims/pdo1pgycxzrrt7dlnhtc",
      title: "Advanced SQL and Query Optimization",
      description:
        "Tackle performance issues in a simulated e-commerce database by identifying bottlenecks and optimizing SQL queries.",
      field: "Database Design",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Advanced",
      duration: 6,
      reviews: [],
      isHiring: true,
      isPublished: false,
      _id: "6874fea559de3084f680404a",
      createdAt: "2025-07-14T12:57:09.433Z",
      updatedAt: "2025-07-14T12:57:09.433Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752498659/upskill/jobSims/ejzt2shgvlu0e0yeev8r.jpg",
      imagePublicId: "upskill/jobSims/ejzt2shgvlu0e0yeev8r",
      title: "Penetration Testing Basics",
      description:
        "Perform basic penetration tests and vulnerability scans in a simulated IT environment to identify and document security weaknesses.\n",
      field: "IT",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Intermediate",
      duration: 5,
      reviews: [],
      isHiring: false,
      isPublished: false,
      _id: "687501e49a9d72968fb1f0fa",
      createdAt: "2025-07-14T13:11:00.131Z",
      updatedAt: "2025-07-14T13:11:00.131Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752498798/upskill/jobSims/qiwfg6hs3a3uypuigovw.jpg",
      imagePublicId: "upskill/jobSims/qiwfg6hs3a3uypuigovw",
      title: "Job Board Platform",
      description:
        "Join a full-stack simulation to build a simple job board with login, posting, and filtering functionalities using React and Express.\n",
      field: "Software Development",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Advanced",
      duration: 8,
      reviews: [],
      isHiring: true,
      isPublished: false,
      _id: "6875026f54357b9d5063c7e2",
      createdAt: "2025-07-14T13:13:19.584Z",
      updatedAt: "2025-07-14T13:13:19.584Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752498995/upskill/jobSims/klpnjhgjydtliubzlov1.jpg",
      imagePublicId: "upskill/jobSims/klpnjhgjydtliubzlov1",
      title: "Developing a Marketing Funnel Strategy",
      description:
        "Create a strategic marketing funnel tailored to a B2C service product, including lead capture, email automation, and conversion tracking.",
      field: "Marketing",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Intermediate",
      duration: 6,
      reviews: [],
      isHiring: false,
      isPublished: false,
      _id: "68750335c560dfaf47030ee8",
      createdAt: "2025-07-14T13:16:37.011Z",
      updatedAt: "2025-07-14T13:16:37.011Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752500641/upskill/jobSims/r1t6fyp01ublixnxmjrl.jpg",
      imagePublicId: "upskill/jobSims/r1t6fyp01ublixnxmjrl",
      title: "Balancing the Books: Accounting for a Small Business",
      description:
        "Simulate managing the finances of a small Ghanaian business by preparing ledgers, reconciling accounts, and creating financial reports.",
      field: "Accounting",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Beginner",
      duration: 3,
      reviews: [],
      isHiring: false,
      isPublished: false,
      _id: "687509a25ff6c96aedf15ac9",
      createdAt: "2025-07-14T13:44:02.784Z",
      updatedAt: "2025-07-14T13:44:02.784Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752500828/upskill/jobSims/c61iwtahcbn76ul4dmdr.jpg",
      imagePublicId: "upskill/jobSims/c61iwtahcbn76ul4dmdr",
      title: "Designing a Community Development Project",
      description:
        "Go through the process of assessing a rural community's needs, setting up objectives, and creating a funding proposal for development intervention.",
      field: "Development Studies",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Intermediate",
      duration: 4,
      reviews: [],
      isHiring: true,
      isPublished: false,
      _id: "68750a5de6a4dafa7db9dea2",
      createdAt: "2025-07-14T13:47:09.382Z",
      updatedAt: "2025-07-14T13:47:09.382Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752501013/upskill/jobSims/idxo9e354etivtgwsn4t.jpg",
      imagePublicId: "upskill/jobSims/idxo9e354etivtgwsn4t",
      title: "Creating an Effective Lesson Plan",
      description:
        "Practice designing and structuring a lesson plan for Junior High School students using the Ghana Education Service (GES) curriculum.",
      field: "Education",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Beginner",
      duration: 2,
      reviews: [],
      isHiring: false,
      isPublished: false,
      _id: "68750b16275ae5ad3aa7f79a",
      createdAt: "2025-07-14T13:50:14.675Z",
      updatedAt: "2025-07-14T13:50:14.675Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752501107/upskill/jobSims/myq2evrhpnsqg9jzcrpo.jpg",
      imagePublicId: "upskill/jobSims/myq2evrhpnsqg9jzcrpo",
      title: "Analyzing National Health Survey Data",
      description:
        "Simulate real-world statistical analysis using public health data, from cleaning the data to presenting findings with charts and recommendations.\n",
      field: "Statistics",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Advanced",
      duration: 5,
      reviews: [],
      isHiring: false,
      isPublished: false,
      _id: "68750b74bfa426d84e86568a",
      createdAt: "2025-07-14T13:51:48.749Z",
      updatedAt: "2025-07-14T13:51:48.749Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752501254/upskill/jobSims/q682mraituspq5rjttt4.jpg",
      imagePublicId: "upskill/jobSims/q682mraituspq5rjttt4",
      title: "Launching a Digital Campaign for a Local Brand",
      description:
        "Plan, budget, and simulate a full-scale digital marketing campaign for a startup selling local organic products in Ghana.",
      field: "Marketing",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Intermediate",
      duration: 3,
      reviews: [],
      isHiring: true,
      isPublished: false,
      _id: "68750c07458b4eac3fbcb9f5",
      createdAt: "2025-07-14T13:54:15.184Z",
      updatedAt: "2025-07-14T13:54:15.184Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752501439/upskill/jobSims/ctofiopljh6jmwmu5qtp.jpg",
      imagePublicId: "upskill/jobSims/ctofiopljh6jmwmu5qtp",
      title: "Managing A School Budget",
      description:
        "Step into the shoes of a school administrator to allocate funds across departments, plan for teacher salaries, and manage logistics.",
      field: "Education",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Intermediate",
      duration: 3,
      reviews: [],
      isHiring: true,
      isPublished: false,
      _id: "68750cbfac42d7a90e2e245a",
      createdAt: "2025-07-14T13:57:19.959Z",
      updatedAt: "2025-07-14T13:57:19.959Z",
      __v: 0,
    },

    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752497383/upskill/jobSims/cnjviu8l2f8sshhmnqrm.jpg",
      imagePublicId: "upskill/jobSims/cnjviu8l2f8sshhmnqrm",
      title: "Legal Case Research ",
      description:
        "Step into the role of a junior legal associate conducting case research, preparing summaries, and briefing senior attorneys.",
      field: "Law",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Beginner",
      duration: 4,
      reviews: [],
      isHiring: false,
      isPublished: false,
      _id: "6874fce8f7bc8115606f2dd5",
      createdAt: "2025-07-14T12:49:44.297Z",
      updatedAt: "2025-07-14T12:49:44.297Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752497383/upskill/jobSims/cnjviu8l2f8sshhmnqrm.jpg",
      imagePublicId: "upskill/jobSims/cnjviu8l2f8sshhmnqrm",
      title: "Legal Case Research ",
      description:
        "Step into the role of a junior legal associate conducting case research, preparing summaries, and briefing senior attorneys.",
      field: "Law",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Beginner",
      duration: 4,
      reviews: [],
      isHiring: false,
      isPublished: false,
      _id: "6874fce8f7bc8115606f2dd5",
      createdAt: "2025-07-14T12:49:44.297Z",
      updatedAt: "2025-07-14T12:49:44.297Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752497827/upskill/jobSims/pdo1pgycxzrrt7dlnhtc.jpg",
      imagePublicId: "upskill/jobSims/pdo1pgycxzrrt7dlnhtc",
      title: "Advanced SQL and Query Optimization",
      description:
        "Tackle performance issues in a simulated e-commerce database by identifying bottlenecks and optimizing SQL queries.",
      field: "Database Design",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Advanced",
      duration: 6,
      reviews: [],
      isHiring: true,
      isPublished: false,
      _id: "6874fea559de3084f680404a",
      createdAt: "2025-07-14T12:57:09.433Z",
      updatedAt: "2025-07-14T12:57:09.433Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752498659/upskill/jobSims/ejzt2shgvlu0e0yeev8r.jpg",
      imagePublicId: "upskill/jobSims/ejzt2shgvlu0e0yeev8r",
      title: "Penetration Testing Basics",
      description:
        "Perform basic penetration tests and vulnerability scans in a simulated IT environment to identify and document security weaknesses.\n",
      field: "IT",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Intermediate",
      duration: 5,
      reviews: [],
      isHiring: false,
      isPublished: false,
      _id: "687501e49a9d72968fb1f0fa",
      createdAt: "2025-07-14T13:11:00.131Z",
      updatedAt: "2025-07-14T13:11:00.131Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752498798/upskill/jobSims/qiwfg6hs3a3uypuigovw.jpg",
      imagePublicId: "upskill/jobSims/qiwfg6hs3a3uypuigovw",
      title: "Job Board Platform",
      description:
        "Join a full-stack simulation to build a simple job board with login, posting, and filtering functionalities using React and Express.\n",
      field: "Software Development",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Advanced",
      duration: 8,
      reviews: [],
      isHiring: true,
      isPublished: false,
      _id: "6875026f54357b9d5063c7e2",
      createdAt: "2025-07-14T13:13:19.584Z",
      updatedAt: "2025-07-14T13:13:19.584Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752498995/upskill/jobSims/klpnjhgjydtliubzlov1.jpg",
      imagePublicId: "upskill/jobSims/klpnjhgjydtliubzlov1",
      title: "Developing a Marketing Funnel Strategy",
      description:
        "Create a strategic marketing funnel tailored to a B2C service product, including lead capture, email automation, and conversion tracking.",
      field: "Marketing",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Intermediate",
      duration: 6,
      reviews: [],
      isHiring: false,
      isPublished: false,
      _id: "68750335c560dfaf47030ee8",
      createdAt: "2025-07-14T13:16:37.011Z",
      updatedAt: "2025-07-14T13:16:37.011Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752500641/upskill/jobSims/r1t6fyp01ublixnxmjrl.jpg",
      imagePublicId: "upskill/jobSims/r1t6fyp01ublixnxmjrl",
      title: "Balancing the Books: Accounting for a Small Business",
      description:
        "Simulate managing the finances of a small Ghanaian business by preparing ledgers, reconciling accounts, and creating financial reports.",
      field: "Accounting",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Beginner",
      duration: 3,
      reviews: [],
      isHiring: false,
      isPublished: false,
      _id: "687509a25ff6c96aedf15ac9",
      createdAt: "2025-07-14T13:44:02.784Z",
      updatedAt: "2025-07-14T13:44:02.784Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752500828/upskill/jobSims/c61iwtahcbn76ul4dmdr.jpg",
      imagePublicId: "upskill/jobSims/c61iwtahcbn76ul4dmdr",
      title: "Designing a Community Development Project",
      description:
        "Go through the process of assessing a rural community's needs, setting up objectives, and creating a funding proposal for development intervention.",
      field: "Development Studies",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Intermediate",
      duration: 4,
      reviews: [],
      isHiring: true,
      isPublished: false,
      _id: "68750a5de6a4dafa7db9dea2",
      createdAt: "2025-07-14T13:47:09.382Z",
      updatedAt: "2025-07-14T13:47:09.382Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752501013/upskill/jobSims/idxo9e354etivtgwsn4t.jpg",
      imagePublicId: "upskill/jobSims/idxo9e354etivtgwsn4t",
      title: "Creating an Effective Lesson Plan",
      description:
        "Practice designing and structuring a lesson plan for Junior High School students using the Ghana Education Service (GES) curriculum.",
      field: "Education",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Beginner",
      duration: 2,
      reviews: [],
      isHiring: false,
      isPublished: false,
      _id: "68750b16275ae5ad3aa7f79a",
      createdAt: "2025-07-14T13:50:14.675Z",
      updatedAt: "2025-07-14T13:50:14.675Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752501107/upskill/jobSims/myq2evrhpnsqg9jzcrpo.jpg",
      imagePublicId: "upskill/jobSims/myq2evrhpnsqg9jzcrpo",
      title: "Analyzing National Health Survey Data",
      description:
        "Simulate real-world statistical analysis using public health data, from cleaning the data to presenting findings with charts and recommendations.\n",
      field: "Statistics",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Advanced",
      duration: 5,
      reviews: [],
      isHiring: false,
      isPublished: false,
      _id: "68750b74bfa426d84e86568a",
      createdAt: "2025-07-14T13:51:48.749Z",
      updatedAt: "2025-07-14T13:51:48.749Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752501254/upskill/jobSims/q682mraituspq5rjttt4.jpg",
      imagePublicId: "upskill/jobSims/q682mraituspq5rjttt4",
      title: "Launching a Digital Campaign for a Local Brand",
      description:
        "Plan, budget, and simulate a full-scale digital marketing campaign for a startup selling local organic products in Ghana.",
      field: "Marketing",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Intermediate",
      duration: 3,
      reviews: [],
      isHiring: true,
      isPublished: false,
      _id: "68750c07458b4eac3fbcb9f5",
      createdAt: "2025-07-14T13:54:15.184Z",
      updatedAt: "2025-07-14T13:54:15.184Z",
      __v: 0,
    },
    {
      imageUrl:
        "https://res.cloudinary.com/dl6ok9s9l/image/upload/v1752501439/upskill/jobSims/ctofiopljh6jmwmu5qtp.jpg",
      imagePublicId: "upskill/jobSims/ctofiopljh6jmwmu5qtp",
      title: "Managing A School Budget",
      description:
        "Step into the shoes of a school administrator to allocate funds across departments, plan for teacher salaries, and manage logistics.",
      field: "Education",
      companyId: "686f97504dbb75697fe6a228",
      companyName: "The Tech Hive",
      tasks: [],
      participants: [],
      level: "Intermediate",
      duration: 3,
      reviews: [],
      isHiring: true,
      isPublished: false,
      _id: "68750cbfac42d7a90e2e245a",
      createdAt: "2025-07-14T13:57:19.959Z",
      updatedAt: "2025-07-14T13:57:19.959Z",
      __v: 0,
    },
  ],
};

export const L = {
  RECRUITERWORKS: [
    {
      icon: <FaTools className="text-xl text-blue-500" />,
      title: "Create Simulations",
      description: "Design custom tasks for students.",
      path: "/recruiter/simulations/create",
    },
    {
      icon: <FaChartBar className="text-xl text-blue-500" />,
      title: "Track Participation",
      description: "Monitor how many students enroll and complete tasks.",
      path: "/recruiter/analytics",
    },
    {
      icon: <FaBullhorn className="text-xl text-blue-500" />,
      title: "Post Internships",
      description: "Advertise verified internship or job opportunities.",
      path: "/recruiter/internships/post",
    },
    {
      icon: <FaComments className="text-xl text-blue-500" />,
      title: "Provide Feedback",
      description:
        "Give structured reviews and ratings on student submissions.",
      path: "/recruiter/feedback",
    },
  ],
  INTERNSHIP: [
    {
      title: "Verified Companies",
      description: "All listings are pre-approved and trusted.",
    },
    {
      title: "Easy Apply",
      description: "Apply with your built-in student profile and resume",
    },
    {
      title: "Status Tracking",
      description: "Know where your application stands at all times",
    },
    {
      title: "Feedback from Recruiters",
      description: "Get valuable input on your submissions and interviews.",
    },
  ],
};

export const user = {
  USERSIDEBAR: [
    {
      icon: <FaTools className="text-xl text-blue-500" />,
      title: "View All Applications",
      path: "/user/all-applications",
    },
    {
      icon: <FaTools className="text-xl text-blue-500" />,
      title: "View All Enrollments",
      path: "/user/all-enrollments",
    },
    {
      icon: <FaChartBar className="text-xl text-blue-500" />,
      title: "Track All Progress",
      path: "/user/track-progress",
    },
  ],
  USERDASHBOARD: [
    {
      icon: <FcProcess className="text-xl text-blue-500" />,
      title: "View All Applications",
      description:
        "View all verified internship or job opportunities applied for by yourself.",
    },
    {
      icon: <FcProcess className="text-xl text-blue-500" />,
      title: "View All Enrolments",
      description: "View all verified  job simulations enrolled in by yourself",
    },
    {
      icon: <FcProcess className="text-xl text-blue-500" />,
      title: "Track Your Progress",
      description: "Advertise verified internship or job opportunities.",
    },
  ],
  USERAPPLICATION: [],
  USERPROGRESS: [],
  USERACHIEVEMENTS: [],
  USERREVIEWS: [],
};

export default K;
